# Configure one or more funding platforms
# Replace placeholders with your org/user handles
github: [your-org, your-username]
open_collective: your-collective
custom: ["https://buymeacoffee.com/your-page"]
