# Automatically label PRs based on changed files
# https://github.com/actions/labeler (v5 format)

area:backend:
  - changed-files:
      - any-glob-to-any-file:
          - tools/tcpwatch/main.go
          - tools/tcpwatch/**/*.go

area:frontend:
  - changed-files:
      - any-glob-to-any-file:
          - tools/tcpwatch/app/src/**
          - tools/tcpwatch/app/electron/**

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

config:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.json'
          - '**/*.yaml'
          - '**/*.yml'
          - '**/*.toml'
