name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
title: "feat: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: scope
    attributes:
      label: Scope & impact
      description: Affected areas, risks, and rollout plan
  - type: textarea
    id: context
    attributes:
      label: Additional context
